x = int(input("First Num is: "))
y = int(input("Second Num is: "))
Result_xPlusy= x+y
Result_xMinusy= x-y
Result_xTimesy= x*y
Result_xdividedBy_y= x/y
print(x,"+",y,"=", Result_xPlusy)
print(x,"-",y,"=", Result_xMinusy)
print(x,"*",y,"=", Result_xTimesy)
print(x,"/",y,"=", Result_xdividedBy_y)
